version: '3.9'

services:
  collector:
    container_name: collector
    build:
      context: ./collect
      dockerfile: ./Dockerfile
      
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=collector
      - POSTGRES_DB=BooksDB
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_IP=books_db

  db:
    image: postgres
    container_name: books_db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: collector
      POSTGRES_DB: BooksDB
    ports:
      - ${POSTGRES_PORT}:5432